name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*" # Push events to matching refs/tags/*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Build Plugin
        run: |
          npm install
          npm run build
          mkdir release
          cp main.js manifest.json release/
          if [ -f styles.css ]; then cp styles.css release/; fi
          cp versions.json release/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/main.js
            release/manifest.json
            release/styles.css
            release/versions.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

